AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution for HTTPS access to satei-app'

Parameters:
  ALBDNSName:
    Type: String
    Default: satei-app-debug-alb-828969271.ap-northeast-1.elb.amazonaws.com
    Description: The DNS name of the ALB

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'CloudFront for satei-app HTTPS'
        Origins:
          - Id: ALBOrigin
            DomainName: !Ref ALBDNSName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              OriginReadTimeout: 60
              OriginKeepaliveTimeout: 60
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          ForwardedValues:
            QueryString: true
            Headers:
              - Host
              - Origin
              - Referer
              - User-Agent
              - CloudFront-Forwarded-Proto
              - X-Forwarded-For
              - X-Forwarded-Proto
            Cookies:
              Forward: all
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 31536000
        PriceClass: PriceClass_200
        HttpVersion: http2
        IPV6Enabled: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /
            ErrorCachingMinTTL: 0

Outputs:
  CloudFrontURL:
    Description: The HTTPS URL for your application
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
  
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution